server:
  port: 8080
spring:
  # Redis Configuration
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:uat}
        prefer-ip-address: false

# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:uat}
    preferIpAddress: ${PREFER_IP:false}
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:registry}:${SERVICE_REGISTRY_PORT:8761}/eureka/

# MongoDB configuration
rp:
  mongo:
    host: ${MONGO_HOST:mongodb}
    port: ${MONGO_PORT:27017}
    dbName: reportportal
    user:
    password:
